# Generated by Django 3.0.1 on 2020-01-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='home',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='post_code',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
