# Generated by Django 3.0.1 on 2020-02-08 16:59

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20200101_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Second_Name', models.CharField(max_length=50, null=True)),
                ('PhoneNumber', models.CharField(max_length=13)),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=150, null=True)),
                ('Data_Time', models.DateTimeField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Profile')),
            ],
        ),
    ]
