# Generated by Django 3.0.1 on 2020-02-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Data_Time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
