# Generated by Django 3.0.1 on 2020-02-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200208_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Data_Time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
