# Generated by Django 3.0.1 on 2020-02-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200222_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Mail',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
