# Generated by Django 3.0.1 on 2020-02-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Choice',
            field=models.CharField(max_length=10),
        ),
    ]
