# Generated by Django 3.0.4 on 2020-05-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_order_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
    ]
