# Generated by Django 3.0.4 on 2020-03-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Mail', models.EmailField(max_length=100, null=True)),
                ('Message', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
