# Generated by Django 3.0.4 on 2020-05-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': "Форма зворотнього зв'язку"},
        ),
    ]
